server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wdt?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 1112
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    properties:
      hibernate:
        ddl-auto: create
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100     # N+1 Problem prevention

  # OAuth
  profiles:
    include: oauth


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
