server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ohwoonwan?serverTimezone=UTC&characterEncoding=UTF-8
    username: oww
    password: oww1!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # OAuth
  profiles:
    include: oauth

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

# File Directory
file:
  dir: /Users/cheoljin/cheoljin-workspace/web-workspace/oww_files/
